### ISSUE TITLE
where is the code?

### ISSUE THREAD

**Issue by hMihaiDavid** [xinabox/bin2uf2#3]

**Comment by brendanvanbreda** [comment]
You can find the application in the releases.
A copy for both Apple and Windows provided.
[releases](https://github.com/xinabox/bin2uf2/releases/tag/v0.1.3)

**Comment by gotfredsen** [comment]
This is not supported any more, but as mention above you can find [the latest release here](https://github.com/xinabox/bin2uf2/releases/latest)
